#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("Tests.Android.Resource", IsApplication=true)]

namespace Tests.Android
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			Xamarin.Android.NUnitLite.Resource.Id.OptionHostName = Tests.Android.Resource.Id.OptionHostName;
			Xamarin.Android.NUnitLite.Resource.Id.OptionPort = Tests.Android.Resource.Id.OptionPort;
			Xamarin.Android.NUnitLite.Resource.Id.OptionRemoteServer = Tests.Android.Resource.Id.OptionRemoteServer;
			Xamarin.Android.NUnitLite.Resource.Id.OptionsButton = Tests.Android.Resource.Id.OptionsButton;
			Xamarin.Android.NUnitLite.Resource.Id.ResultFullName = Tests.Android.Resource.Id.ResultFullName;
			Xamarin.Android.NUnitLite.Resource.Id.ResultMessage = Tests.Android.Resource.Id.ResultMessage;
			Xamarin.Android.NUnitLite.Resource.Id.ResultResultState = Tests.Android.Resource.Id.ResultResultState;
			Xamarin.Android.NUnitLite.Resource.Id.ResultStackTrace = Tests.Android.Resource.Id.ResultStackTrace;
			Xamarin.Android.NUnitLite.Resource.Id.ResultsFailed = Tests.Android.Resource.Id.ResultsFailed;
			Xamarin.Android.NUnitLite.Resource.Id.ResultsId = Tests.Android.Resource.Id.ResultsId;
			Xamarin.Android.NUnitLite.Resource.Id.ResultsIgnored = Tests.Android.Resource.Id.ResultsIgnored;
			Xamarin.Android.NUnitLite.Resource.Id.ResultsInconclusive = Tests.Android.Resource.Id.ResultsInconclusive;
			Xamarin.Android.NUnitLite.Resource.Id.ResultsMessage = Tests.Android.Resource.Id.ResultsMessage;
			Xamarin.Android.NUnitLite.Resource.Id.ResultsPassed = Tests.Android.Resource.Id.ResultsPassed;
			Xamarin.Android.NUnitLite.Resource.Id.ResultsResult = Tests.Android.Resource.Id.ResultsResult;
			Xamarin.Android.NUnitLite.Resource.Id.RunTestsButton = Tests.Android.Resource.Id.RunTestsButton;
			Xamarin.Android.NUnitLite.Resource.Id.TestSuiteListView = Tests.Android.Resource.Id.TestSuiteListView;
			Xamarin.Android.NUnitLite.Resource.Layout.options = Tests.Android.Resource.Layout.options;
			Xamarin.Android.NUnitLite.Resource.Layout.results = Tests.Android.Resource.Layout.results;
			Xamarin.Android.NUnitLite.Resource.Layout.test_result = Tests.Android.Resource.Layout.test_result;
			Xamarin.Android.NUnitLite.Resource.Layout.test_suite = Tests.Android.Resource.Layout.test_suite;
			Salesforce.Resource.String.library_name = Tests.Android.Resource.String.library_name;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050001
			public const int OptionHostName = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int OptionPort = 2131034114;
			
			// aapt resource value: 0x7f050000
			public const int OptionRemoteServer = 2131034112;
			
			// aapt resource value: 0x7f050010
			public const int OptionsButton = 2131034128;
			
			// aapt resource value: 0x7f05000a
			public const int ResultFullName = 2131034122;
			
			// aapt resource value: 0x7f05000c
			public const int ResultMessage = 2131034124;
			
			// aapt resource value: 0x7f05000b
			public const int ResultResultState = 2131034123;
			
			// aapt resource value: 0x7f05000d
			public const int ResultStackTrace = 2131034125;
			
			// aapt resource value: 0x7f050006
			public const int ResultsFailed = 2131034118;
			
			// aapt resource value: 0x7f050003
			public const int ResultsId = 2131034115;
			
			// aapt resource value: 0x7f050007
			public const int ResultsIgnored = 2131034119;
			
			// aapt resource value: 0x7f050008
			public const int ResultsInconclusive = 2131034120;
			
			// aapt resource value: 0x7f050009
			public const int ResultsMessage = 2131034121;
			
			// aapt resource value: 0x7f050005
			public const int ResultsPassed = 2131034117;
			
			// aapt resource value: 0x7f050004
			public const int ResultsResult = 2131034116;
			
			// aapt resource value: 0x7f05000f
			public const int RunTestsButton = 2131034127;
			
			// aapt resource value: 0x7f05000e
			public const int TestSuiteListView = 2131034126;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int options = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int results = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int test_result = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int test_suite = 2130903043;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040000
			public const int library_name = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
